version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - static:/app/backend/static
    restart: always

    ports:
      - 8000:8000
    env_file:
      - ./backend/.env


  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - node_modules:/app/frontend/node_modules
    depends_on:
      - backend
    restart: always

    ports:
      - 3000:3000


  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - static:/app/backend/static
    restart: always
    ports:
      - 80:80


volumes:
  static:
  node_modules: